# SPDX-FileCopyrightText: 2026 Adam Bogdan Boczek
# SPDX-License-Identifier: GPL-3.0-or-later

version: 2

project_name: c8volt

before:
  hooks:
    - go mod tidy

builds:
  - id: c8volt
    main: .
    binary: c8volt
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X github.com/grafvonb/c8volt/cmd.version={{.Version}}
        -X github.com/grafvonb/c8volt/cmd.commit={{.Commit}}
        -X github.com/grafvonb/c8volt/cmd.date={{.Date}}
        -X github.com/grafvonb/c8volt/cmd.builtBy=GoReleaser

archives:
  - id: artifacts
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - src: README.md
      - src: LICENSE
      - src: config/templates/config.example.yaml
        dst: config.example.yaml

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: desc
  filters:
    exclude:
      - "^Merge pull request #[0-9]+"
      - "^docs(\\(.+\\))?:"
      - "^test(\\(.+\\))?:"
      - "^chore(\\(.+\\))?:"
      - "^refactor(\\(.+\\))?:"
