title: "c8volt: Camunda 8 Operations CLI"
description: "The tool for Camunda 8 admins and developers to verify outcomes."

theme: just-the-docs

markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..3

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

url: "https://c8volt.info"
baseurl: ""

color_scheme: c8volt
search_enabled: true
search.heading_level: 2
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "c8volt documentation"

aux_links:
  "GitHub":
    - "https://github.com/grafvonb/c8volt"
  "Releases":
    - "https://github.com/grafvonb/c8volt/releases"

nav_external_links:
  - title: CLI Reference
    url: /cli/
  - title: README
    url: https://github.com/grafvonb/c8volt/blob/main/README.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

  - scope:
      path: "cli"
      type: "pages"
    values:
      layout: default
      nav_exclude: true
