# SPDX-FileCopyrightText: 2026 Adam Bogdan Boczek
# SPDX-License-Identifier: GPL-3.0-or-later

source "https://rubygems.org"

gem "jekyll", "= 3.10.0"
gem "just-the-docs", "= 0.12.0"
gem "jekyll-sitemap", "= 1.4.0"
gem "jekyll-seo-tag", "= 2.8.0"
gem "kramdown", "= 2.4.0"
gem "kramdown-parser-gfm", "= 1.1.0"
gem "base64"
gem "bigdecimal", "= 3.3.1"
gem "logger"
gem "webrick" # needed for Ruby 4+
